apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: velocity-tracker
    app: velocity-tracker
  name: velocity-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: velocity-tracker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: velocity-tracker
    spec:
      containers:
      - image: corvimae/gdq-tracker:master
        imagePullPolicy: Always
        name: velocity-tracker
        envFrom:
        - secretRef:
            name: velocity-tracker-secrets
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
